# Generated by Django 3.0.8 on 2020-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='member_limit',
            new_name='members_limit',
        ),
    ]
