# Generated by Django 3.0.8 on 2020-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
